
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_backend_development
  username: postgres
  password: 5001
  port: 5432

  
test:
  <<: *default
  database: hello_rails_backend_test
  username: postgres
  password: 5001


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: hello_rails_backend_production
  username: hello_rails_backend
  password: <%= ENV["HELLO_RAILS_DATABASE_PASSWORD"] %>